- name: Install Dependencies
  run: composer install --no-dev --optimize-autoloader


name: Build and Deploy Laravel to Azure

on:
  push:
    branches:
      - main   # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # 2. Setup PHP 8.3 with required extensions for Laravel
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, xml, ctype, json, tokenizer, pdo, mysql

      # 3. Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Run Laravel optimization (optional but recommended)
      - name: Cache Laravel Config & Routes
        run: |
          php artisan config:cache || true
          php artisan route:cache || true
          php artisan view:cache || true

      # 5. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<YOUR_AZURE_WEBAPP_NAME>' # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

